complete -c vmail-cli -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_use_subcommand" -f -a "user" -d 'User management for the vmail database'
complete -c vmail-cli -n "__fish_use_subcommand" -f -a "domain" -d 'Manage domains for a vmail database'
complete -c vmail-cli -n "__fish_use_subcommand" -f -a "alias" -d 'Manage aliases for the vmail database'
complete -c vmail-cli -n "__fish_use_subcommand" -f -a "completions" -d 'Generates completion scripts for your shell'
complete -c vmail-cli -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -s d -l domain -d 'Domain to use for the user subcommands, default can be specified in \'.env\' file. E.g. mydomain.tld'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -f -a "show" -d 'Show user account(s)'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -f -a "add" -d 'Add a user to the database'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -f -a "remove" -d 'Remove a user from the database, will also delete all aliases for the user'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -f -a "password" -d 'Change the password for given user'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -f -a "edit" -d 'Edit a user account entry'
complete -c vmail-cli -n "__fish_seen_subcommand_from user" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s v -l verbose -d 'Verbose output (include aliases)'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s q -l quota -d 'Quota for user account in MB (Megabyte), default is 0 which is unlimited'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s d -l disabled -d 'Disable the user, just add it to the database'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s s -l send-only -d 'Allow the new user only to send email but not receive any.'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s f -l force -d 'Force the deleting the given user'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s v -l verbose -d 'Verbose output what has been deleted'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from password" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from password" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s q -l quota -d 'Quota for user account in MB (Megabyte), 0 is unlimited'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s d -l disable -d 'Disable given user'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s e -l enable -d 'Enable given user'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s s -l send-only -d 'Allow user only to send'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s r -l send-receive -d 'Allow user to send and receive'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from edit" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from domain" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from domain" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from domain" -f -a "show" -d 'Show domains'
complete -c vmail-cli -n "__fish_seen_subcommand_from domain" -f -a "add" -d 'Add a new domain to the database'
complete -c vmail-cli -n "__fish_seen_subcommand_from domain" -f -a "remove" -d 'Remove a domain from the database, this will also delete all related users.'
complete -c vmail-cli -n "__fish_seen_subcommand_from domain" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s u -l with-users -d 'Show all users for the domain'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s a -l with-aliases -d 'Show all aliases for the users'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s f -l force -d 'Force the deleting the given domain'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s v -l verbose -d 'Verbose output what has been deleted'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from alias" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from alias" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from alias" -f -a "show" -d 'Show aliases for user'
complete -c vmail-cli -n "__fish_seen_subcommand_from alias" -f -a "add" -d 'Add an alias to an existing user account'
complete -c vmail-cli -n "__fish_seen_subcommand_from alias" -f -a "remove" -d 'Remove an alias from the database'
complete -c vmail-cli -n "__fish_seen_subcommand_from alias" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from show" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s d -l disabled -d 'Set alias to disabled'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from add" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from remove" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c vmail-cli -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
